version: "3"

services:
  web:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    ports:
      - 5000:5000
    volumes:
      - .:/usr/src/app
    depends_on:
      - mysql
    links:
      - mysql

  mysql:
    image: mysql:8.0
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    container_name: flask-mysql
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=flask
      - MYSQL_USER=flask
      - MYSQL_PASSWORD=flask
