version: "3"

services:

  mysql:
    image: mysql:latest
    container_name: flask-mysql
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=flask
      - MYSQL_USER=flask
      - MYSQL_PASSWORD=flask


  web:
    build: ./docker/python/
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    depends_on:
      - mysql
    links:
      - mysql
