# Generated by Django 3.2.6 on 2021-08-05 14:51

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_network', '0002_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(blank=True, choices=[('summer', 'Summer menu'), ('autumn', 'Autumn menu'), ('winter', 'Winter menu'), ('spring', 'Spring menu'), ('year', 'Regular menu')], default='year', max_length=15)),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
            },
        ),
        migrations.AddField(
            model_name='restaurant',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('home_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citizens', to='food_network.city')),
                ('work_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='food_network.restaurant')),
            ],
            options={
                'verbose_name': 'Worker',
                'verbose_name_plural': 'Workers',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ingredients', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=25), size=None)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('category', models.ManyToManyField(to='food_network.Menu')),
                ('place', models.ManyToManyField(related_name='dishes', to='food_network.Restaurant')),
            ],
            options={
                'verbose_name': 'Dish',
                'verbose_name_plural': 'Dishes',
            },
        ),
    ]
