# Generated by Django 3.2.6 on 2021-08-13 19:05

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dealers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=75)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('published', 'Published'), ('sold', 'Sold'), ('archived', 'Archived')], default='pending', max_length=15)),
                ('engine_type', models.CharField(max_length=15)),
                ('pollutant_class', models.CharField(blank=True, choices=[('A+', 'class A+'), ('A', 'class A'), ('B', 'class B'), ('C', 'class C'), ('D', 'class D'), ('E', 'class E'), ('F', 'class F'), ('G', 'class G')], default='G', max_length=10)),
                ('price', models.PositiveIntegerField()),
                ('doors', models.PositiveIntegerField()),
                ('capacity', models.IntegerField()),
                ('gear_case', models.CharField(max_length=25)),
                ('number', models.CharField(max_length=15, null=True)),
                ('sitting_place', models.PositiveIntegerField()),
                ('first_registration_date', models.DateTimeField()),
                ('engine_power', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
            },
        ),
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(blank=True, choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Biofuel', 'Biofuel'), ('Gas', 'Liquified Petroleum Gas'), ('Hybrid', 'Plug-in Hybrid Electric Vehicle'), ('Electric', 'Battery Electric Vehicle')], default='Petrol', max_length=50)),
            ],
            options={
                'verbose_name': 'Fuel type',
                'verbose_name_plural': 'Fuel types',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('Category M light-duty', 'Passenger cars and vans'), ('Category M heavy-duty', 'Trucks, buses, and coaches'), ('Category N', 'Vehicles carrying goods'), ('Category L', '2- and 3-wheel vehicles and quadricycles'), ('Category T', 'Agricultural and forestry tractors and their trailers')], default='Category M light-duty', max_length=250)),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(blank=True, upload_to='pictures')),
                ('position', models.CharField(max_length=15)),
                ('metadata', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='cars.car')),
            ],
            options={
                'verbose_name': 'Picture',
                'verbose_name_plural': 'Pictures',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='cars.brand')),
            ],
            options={
                'verbose_name': 'Model',
                'verbose_name_plural': 'Models',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.carmodel'),
        ),
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.ManyToManyField(blank=True, to='cars.Property'),
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.color'),
        ),
        migrations.AddField(
            model_name='car',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='dealers.dealer'),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.fueltype'),
        ),
    ]
