# Generated by Django 3.2.6 on 2021-08-09 11:40

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('car_showroom', '0002_auto_20210807_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=75)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('published', 'Published'), ('sold', 'Sold'), ('archived', 'Archived')], default='pending', max_length=15)),
                ('engine_type', models.CharField(max_length=15)),
                ('pollutant_class', models.CharField(blank=True, choices=[('class A+', 'A+'), ('class A', 'A'), ('class B', 'B'), ('class C', 'C'), ('class D', 'D'), ('class E', 'E'), ('class F', 'F'), ('class G', 'G')], default='class G', max_length=10)),
                ('price', models.PositiveIntegerField()),
                ('fuel_type', models.CharField(blank=True, choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Biofuel', 'Biofuel'), ('Gas', 'Liquified Petroleum Gas'), ('Hybrid', 'Plug-in Hybrid Electric Vehicle'), ('Electric', 'Battery Electric Vehicle')], default='Petrol', max_length=50)),
                ('doors', models.PositiveIntegerField()),
                ('capacity', models.IntegerField()),
                ('gear_case', models.CharField(max_length=25)),
                ('number', models.CharField(max_length=15)),
                ('sitting_place', models.PositiveIntegerField()),
                ('first_registration_date', models.DateTimeField()),
                ('engine_power', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
            },
        ),
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'News Letter',
                'verbose_name_plural': 'News Letters',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('Category M light-duty', 'Passenger cars and vans'), ('Category M heavy-duty', 'Trucks, buses, and coaches'), ('Category N', 'Vehicles carrying goods'), ('Category L', '2- and 3-wheel vehicles and quadricycles'), ('Category T', 'Agricultural and forestry tractors and their trailers')], default='Category M light-duty', max_length=250)),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(blank=True, upload_to='pictures')),
                ('position', models.CharField(max_length=15)),
                ('metadata', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='car_showroom.car')),
            ],
            options={
                'verbose_name': 'Picture',
                'verbose_name_plural': 'Pictures',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('received', 'Received'), ('waiting', 'Waiting'), ('active', 'In progress'), ('closed', 'Closed')], default='waiting', max_length=15)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('message', models.TextField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='car_showroom.car')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='car_showroom.brand')),
            ],
            options={
                'verbose_name': 'Model',
                'verbose_name_plural': 'Models',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='car_showroom.carmodel'),
        ),
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.ManyToManyField(blank=True, to='car_showroom.Property'),
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='car_showroom.color'),
        ),
        migrations.AddField(
            model_name='car',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='car_showroom.dealer'),
        ),
    ]
