# Generated by Django 3.2.6 on 2021-08-10 23:51

from django.db import migrations, models
import django.db.models.deletion


def fuel_type_handler(apps, schema_editor):
    Car = apps.get_model('car_showroom', 'Car')
    FuelType = apps.get_model('car_showroom', 'FuelType')

    for car in Car.objects.all():
        if FuelType.objects.filter(fuel_type=car.fuel_type).count():
            car.fuel_type = FuelType.objects.get(fuel_type=car.fuel_type).id
        else:
            FuelType.objects.create(fuel_type=car.fuel_type)
            car.fuel_type = FuelType.objects.get(fuel_type=car.fuel_type).id
        car.save()


class Migration(migrations.Migration):

    dependencies = [
        ('car_showroom', '0003_auto_20210809_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(blank=True, choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'),
                                                                    ('Biofuel', 'Biofuel'),
                                                                    ('Gas', 'Liquified Petroleum Gas'),
                                                                    ('Hybrid', 'Plug-in Hybrid Electric Vehicle'),
                                                                    ('Electric', 'Battery Electric Vehicle')],
                                               default='Petrol', max_length=50)),
            ],
            options={
                'verbose_name': 'Fuel type',
                'verbose_name_plural': 'Fuel types',
            },
        ),
        migrations.AlterField(
            model_name='car',
            name='number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='pollutant_class',
            field=models.CharField(blank=True,
                                   choices=[('A+', 'class A+'), ('A', 'class A'), ('B', 'class B'), ('C', 'class C'),
                                            ('D', 'class D'), ('E', 'class E'), ('F', 'class F'), ('G', 'class G')],
                                   default='G', max_length=10),
        ),
        migrations.RunPython(fuel_type_handler),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars',
                                    to='car_showroom.fueltype'),
        ),
    ]
